// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPLjWjc2apE6J8QoBjLRZcs58WGYL4m7U',
    appId: '1:352474855554:web:9a9037ca3cf21791b5dc9b',
    messagingSenderId: '352474855554',
    projectId: 'cryptoappwatch',
    authDomain: 'cryptoappwatch.firebaseapp.com',
    storageBucket: 'cryptoappwatch.firebasestorage.app',
    measurementId: 'G-X6CLFMRXYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARwKFvcphBVWx9Vwa5byycHNsgqtGa_OA',
    appId: '1:352474855554:android:2bf15da032946701b5dc9b',
    messagingSenderId: '352474855554',
    projectId: 'cryptoappwatch',
    storageBucket: 'cryptoappwatch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFg_j2cJ6KndvQJyB8Orrt4fYIJgVtueo',
    appId: '1:352474855554:ios:56ba74c0da40f6e0b5dc9b',
    messagingSenderId: '352474855554',
    projectId: 'cryptoappwatch',
    storageBucket: 'cryptoappwatch.firebasestorage.app',
    iosBundleId: 'com.example.cryptoValue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFg_j2cJ6KndvQJyB8Orrt4fYIJgVtueo',
    appId: '1:352474855554:ios:56ba74c0da40f6e0b5dc9b',
    messagingSenderId: '352474855554',
    projectId: 'cryptoappwatch',
    storageBucket: 'cryptoappwatch.firebasestorage.app',
    iosBundleId: 'com.example.cryptoValue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPLjWjc2apE6J8QoBjLRZcs58WGYL4m7U',
    appId: '1:352474855554:web:74745ddaa72a1777b5dc9b',
    messagingSenderId: '352474855554',
    projectId: 'cryptoappwatch',
    authDomain: 'cryptoappwatch.firebaseapp.com',
    storageBucket: 'cryptoappwatch.firebasestorage.app',
    measurementId: 'G-SN8B8L7KPJ',
  );

}